base_url= "https://f5.maatt.fr"
title= "Broadcast 3,4 Wiki"
compile_sass= true
build_search_index= true

[markdown]
highlight_code= false
render_emoji= true
external_links_target_blank= true
external_links_no_follow= true
external_links_no_referrer= true

[search]
include_title= true
include_description= true
include_content= true
